
title: Resume - Derek Mortimer
url: 'https://pyoio.github.com'
baseurl: '/cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
# style: styles-3
style: styles-4
# style: styles-5
# style: styles-6


#Profile information
name: Derek Mortimer
tagline: Principal Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: derek.mortimer@me.com
phone: 07515 353 444
# website: pyoio.github.io
linkedin: derekmortimer
github: pyoio
twitter: derekmortimer

#Update all the sections by editing the files inside _includes folder.
